language: python

matrix:
  include:
    - python: '2.7'
      env: TEST_SUITE=python2
    - python: '3.6'
      env: TEST_SUITE=python3 TYPE_CHECK=1 FLAKE8=1
    - python: "nightly"
      env: TEST_SUITE=python3 TYPE_CHECK=1 FLAKE8=1

install:
  - if [[ -n "$TYPE_CHECK" ]]; then python3 -m pip install mypy ; fi
  - if [[ -n "FLAKE8" ]]; then python3 -m pip install flake8 ; fi

script:
  - ./run_tests.sh

